apiVersion: v1
kind: Pod
metadata:
  name: gitmark4
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: k8s-volume
      mountPath: /usr/share/nginx/html/index.html
      subPath: index.html # Mount only the file
  initContainers:
  - name: git-clone
    image: alpine/git
    command:
    - sh
    - -c
    - |
      git clone https://github.com/SuvraSandeep/kubernetes.git /tmp/repo;
      cp /tmp/repo/index.html /data/index.html
    volumeMounts:
    - name: k8s-volume
      mountPath: /data
  volumes:
  - name: k8s-volume
    emptyDir: {}
